config/routes.rb
if Rails::VERSION::MAJOR >= 3
  RedmineApp::Application.routes.draw do
    resources :delays
  end
else
  ActionController::Routing::Routes.draw do |map|
    map.resources :delays
  end
end

app/models/delay.rb
class Delay < ActiveRecord::Base
  unloadable

  belongs_to :user
  belongs_to :author, :class_name => 'User', :foreign_key => 'author_id'

  validates_presence_of :user_id, :author_id, :arrival_time, :delay_on

  scope :like_username, lambda {|q|
    if q.present?
      {:conditions =>
        ["LOWER(users.firstname) LIKE :p OR users.firstname LIKE :p OR LOWER(users.lastname) LIKE :p OR users.lastname LIKE :p",
         {:p => "%#{q.to_s.downcase}%"}],
        :joins => :user}
    end
  }

  scope :eql_field, lambda{ |q, field|
    where(field => q) if q.present? && field.present?
  }

  def to_s
    user ? user.name : ""
  end

end

app/controllers/delays_controller.rb
class DelaysController < ApplicationController
  unloadable
  before_filter :require_delays_manager
  before_filter :new_delay, :only => [:new, :index, :create]
  before_filter :find_delay, :only => [:edit, :update, :show, :destroy]

  helper :sort
  include SortHelper
  helper :delays
  include DelaysHelper

  def index
    sort_init 'created_on', 'desc'
    sort_update({
      'arrival_time' => 'arrival_time', 'delay_on' => 'delay_on',
      'user_id' => ["users.lastname", "users.firstname"],
#FIXME      'author_id' => ["users.lastname", "users.firstname"],
      'created_on' => 'created_on'})

    @limit = per_page_option

    @scope = Delay.time_period(params[:delay_on], :delay_on).
      like_username(params[:user_name]).
      eql_field(params[:author_id], :author_id)

    @count = @scope.count

    @pages = begin
      Paginator.new @count, @limit, params[:page]
    rescue
      Paginator.new self, @count, @limit, params[:page]
    end
    @offset ||= begin
      @pages.offset
    rescue
      @pages.current.offset
    end

    @delays =  @scope.find  :all,
                            :order => sort_clause,
                            :limit  =>  @limit,
                            :offset =>  @offset,
                            :joins => :user
    respond_to do |format|
      format.html{ render :action => :index }
      format.csv{ send_data(index_to_csv, :type => 'text/csv; header=present', :filename => Date.today.strftime("delays_%Y-%m-%d.csv")) }
    end
  end

  def new
  end

  def create
    if @delay.save
      flash[:notice] = l(:notice_successful_create)
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end
  end

  def edit
  end

  def update
    if @delay.update_attributes(params[:delay])
      flash[:notice] = l(:notice_successful_update)
      redirect_to :action => :index
    else
      render :action => :edit
    end
  end

  def destroy
    @delay.destroy
    redirect_to :action => :index
  rescue
    flash[:error] = l(:error_unable_delete_delay)
    redirect_to :action => :index
  end

  private
    def new_delay
      @delay = Delay.new((params[:delay] || {}).merge(:author_id => User.current.id))
    end

    def find_delay
      @delay = Delay.find(params[:id])
    end

    def require_delays_manager
      (render_403; return false) unless User.current.is_delays_manager?
    end
end

app/helpers/delays_helper.rb
module DelaysHelper

  def time_periods
    %w{yesterday last_week this_week last_month this_month last_year this_year}
  end

  def index_to_csv
    decimal_separator = l(:general_csv_decimal_separator)
    export = FCSV.generate(:col_sep => l(:general_csv_separator)) do |csv|
      # csv header fields
      csv << [ 
        l(:field_user), 
        l(:field_delay_on),
        l(:field_arrival_time),
        l(:field_reason),
        l(:field_author),
        l(:field_created_on),
        l(:field_updated_on),        
      ]
      
      # csv lines
      @scope.all(:order => "arrival_time, delay_on").each do |object|
        csv << [
          object.user.name,
          format_date(object.delay_on),
          format_time(object.arrival_time, false),
          object.reason,
          object.author.name,          
          format_time(object.created_on),
          format_time(object.updated_on)
        ]
      end
    end
    export    
  end

end

app/views/delays/_form.html.haml
= error_messages_for @delay

.box.tabular
  %p= f.select :user_id, User.find(:all, :order => "lastname, firstname").map {|c| [c.name, c.id]}, :required => true, :prompt => t(:prompt_please_select)
  %p
    = f.text_field :delay_on, :size => 10, :required => true
    = calendar_for('delay_delay_on')
  %p
    %label{:for=>'delay_arrival_time'}
      = l(:field_arrival_time)
      %span{:class => :required}= '*'
    = f.time_select :arrival_time, {:minute_step => 5}
  %p
    = f.text_field :reason, :cols => 60

app/views/delays/_settings.html.haml
%p
  %label= l(:label_delay_manager_plural)
  = select_tag("settings[principal_id]", principals_options_for_select(Principal.active.all, (Principal.find(@settings[:principal_id]) rescue nil)), prompt: t(:prompt_please_select))

app/views/delays/edit.html.haml
%h2
  = link_to l(:label_delay_plural), :action => :index
  &#187;
  =h @delay

- form = labelled_form_for @delay do |f|
  = render :partial => 'form', :locals => {:f => f}
  = submit_tag l(:button_save)
= form if Rails::VERSION::MAJOR >= 3  

app/views/delays/index.html.haml
.contextual
  = link_to l(:label_delay_new), new_delay_path, :class => 'icon icon-add'

%h2=l(:label_delay_plural)

%form{:method => :get}
  %fieldset
    %legend= l(:label_filter_plural)

    = hidden_field_tag :delay_on, params[:delay_on]

    %label{:for=>'author_id'}= l(:field_author) + ":"
    %select{:id => 'author_id', :name => 'author_id', :class => "small", :onchange => "this.form.submit(); return false;"}
      %option
      - VacationManager.all.map(&:user).compact.sort_by(&:name).each do |user|
        - if params[:author_id].to_i == user.id
          %option{:value => user.id, :selected => "selected"}
            = user.name
        - else
          %option{:value => user.id}
            = user.name

    &nbsp;

    %label{:for=>'user_name'}= l(:field_user) + ":"
    = text_field_tag 'user_name', params[:user_name], :size => 30

    = submit_tag l(:button_apply), :class => "small", :name => nil
    = link_to l(:button_clear), {:action => params[:action]}, :class => 'icon icon-reload'

    - %w{delay_on}.each do |type_date|
      %br
      %label=l(:"field_#{type_date}") + ":"
      - Delay.time_periods.each do |key|
        - if params[:"#{type_date}"] == key
          %strong
            = l(:"label_period_#{key}")
        - else
          = link_to l(:"label_period_#{key}"), params.merge( :"#{type_date}" => key )
        = "(#{Delay.time_period(key, :"#{type_date}").count}) /"


&nbsp;

- if @delays.any?
  %table.list
    %thead
      %tr
        =sort_header_tag :user_id, :caption => l(:field_user)
        =sort_header_tag :delay_on, :caption => l(:field_delay_on)
        =sort_header_tag :arrival_time, :caption => l(:field_arrival_time)
        %th=l(:field_reason)
        %th=l(:field_author)
        =sort_header_tag :created_on, :caption => l(:field_created_on)
        %th
    %tbody
      - @delays.each do |delay|
        %tr{:class=>cycle("odd", "even")}
          %td
            - if delay.user
              = link_to_user delay.user
          %td{:align=>"center"}= format_date(delay.delay_on)
          %td{:align=>"center"}= format_time(delay.arrival_time, false)
          %td
            = h(delay.reason)
          %td
            - if delay.author
              = link_to_user delay.author
          %td{:align=>"center"}= format_time(delay.created_on)
          %td.buttons
            = link_to l(:button_update), {:action => 'edit', :id => delay.id}, :class => 'icon icon-edit'
            = link_to(l(:button_delete), delay_path(delay), :method => :delete, :confirm => l(:text_are_you_sure), :class => 'icon icon-del')

  %p.pagination= pagination_links_full @pages, @count

  %p.other-formats
    = l(:label_export_to)
    = link_to 'CSV', params.merge(:format => :csv)
- else
  %p.nodata
    = l(:label_no_data)

- html_title(l(:label_delay_plural))

app/views/delays/new.html.haml
%h2
  = link_to l(:label_delay_plural), :action => :index
  &#187;
  =l(:label_delay_new)

- form = labelled_form_for @delay do |f|
  = render :partial => 'form', :locals => {:f => f}
  = submit_tag l(:button_create)
= form if Rails::VERSION::MAJOR >= 3